"""The haproxy.cfg renderer."""

from datetime import datetime
from datetime import timezone
import re

from .base import CERT_DIR
from .config import merged
from .util import _by_id, _sec, cert_path
from . import access

# --------------------------------------------------------------------------

COND_MAP = {
    "host_matches":     lambda c: "hdr(host) -i %s" % c.get("value", ""),
    "host_starts_with": lambda c: "hdr_beg(host) -i %s" % c.get("value", ""),
    "host_ends_with":   lambda c: "hdr_end(host) -i %s" % c.get("value", ""),
    "path_matches":     lambda c: "path %s" % c.get("value", ""),
    "path_starts_with": lambda c: "path_beg %s" % c.get("value", ""),
    "path_ends_with":   lambda c: "path_end %s" % c.get("value", ""),
    "path_contains":    lambda c: "path_sub %s" % c.get("value", ""),
    "url_parameter":    lambda c: "url_param(%s) -i %s" % (c.get("param", ""), c.get("value", "")),
    "http_header":      lambda c: "hdr(%s) -i %s" % (c.get("param", ""), c.get("value", "")),
    "source_ip":        lambda c: "src %s" % c.get("value", ""),
    "ssl_sni":          lambda c: "req.ssl_sni -i %s" % c.get("value", ""),
    "custom":           lambda c: c.get("value", ""),
}


def _rule_line(rule, conds, backends):
    suffix = ""
    cond_ids = rule.get("conditions") or []
    names = []
    for cid in cond_ids:
        c = conds.get(cid)
        if c:
            names.append(("!" if c.get("negate") else "") + "acl_" + _sec(c["name"]))
    if names:
        joiner = " or " if rule.get("operator") == "or" else " "
        suffix = " %s %s" % (rule.get("test", "if"), joiner.join(names))
    t = rule.get("type")
    p1, p2 = rule.get("param1", ""), rule.get("param2", "")
    if t == "use_backend":
        be = backends.get(rule.get("backend"))
        return ("use_backend be_%s%s" % (_sec(be["name"]), suffix)) if be else None
    if t == "redirect_scheme_https":
        return "http-request redirect scheme https code 301" + suffix
    if t == "redirect_location":
        return "http-request redirect location %s code 302%s" % (p1, suffix)
    if t == "http_request_deny":
        return "http-request deny" + suffix
    if t == "http_request_set_header":
        return "http-request set-header %s %s%s" % (p1, p2, suffix)
    if t == "http_request_del_header":
        return "http-request del-header %s%s" % (p1, suffix)
    if t == "http_response_set_header":
        return "http-response set-header %s %s%s" % (p1, p2, suffix)
    if t == "tcp_request_content_accept":
        return "tcp-request content accept" + suffix
    if t == "tcp_request_content_reject":
        return "tcp-request content reject" + suffix
    if t == "custom":
        return (p1 + suffix) if p1 else None
    return None


# Two words per certificate against HAProxy's 64-word line limit, less the
# words the bind line already uses. Twenty is comfortably under it.
MAX_INLINE_CERTS = 20


def render_haproxy(cfg):
    """What this node serves: the shared configuration plus its own objects.

    Merged here rather than by every caller, so nothing can render a
    configuration that leaves out the service publishing this node's own
    management UI.
    """
    cfg = merged(cfg)
    hp = cfg["haproxy"]
    st = hp["settings"]
    ac = cfg["acme"]["settings"]
    servers = _by_id(hp["servers"])
    backends = _by_id(hp["backends"])
    checks = _by_id(hp["healthchecks"])
    conds = _by_id(hp["conditions"])
    rules = _by_id(hp["rules"])
    certs = _by_id(cfg["acme"]["certificates"])
    acme_on = bool(ac.get("enabled") and ac.get("haproxy_integration"))

    L = []
    A = L.append
    A("# Generated by haproxy-manager at %s" % datetime.now(timezone.utc).isoformat(timespec="seconds"))
    A("# Do not edit by hand -- changes are overwritten on Apply.")
    A("")
    A("global")
    A("    log /dev/log local0")
    A("    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners")
    A("    stats timeout 30s")
    A("    maxconn %s" % (st.get("maxconn") or 4000))
    if st.get("nbthread"):
        A("    nbthread %s" % st["nbthread"])
    if st.get("hard_stop_after"):
        A("    hard-stop-after %s" % st["hard_stop_after"])
    if st.get("ssl_min_ver"):
        A("    ssl-default-bind-options ssl-min-ver %s" % st["ssl_min_ver"])
    if st.get("ssl_ciphers"):
        A("    ssl-default-bind-ciphers %s" % st["ssl_ciphers"])
    for ln in (st.get("custom_global") or "").splitlines():
        if ln.strip():
            A("    " + ln.strip())
    A("")
    A("defaults")
    A("    log global")
    A("    option dontlognull")
    if st.get("redispatch", True):
        A("    option redispatch")
    A("    retries %s" % st.get("retries", 3))
    A("    timeout connect %s" % (st.get("timeout_connect") or "5s"))
    A("    timeout client %s" % (st.get("timeout_client") or "50s"))
    A("    timeout server %s" % (st.get("timeout_server") or "50s"))
    for ln in (st.get("custom_defaults") or "").splitlines():
        if ln.strip():
            A("    " + ln.strip())
    A("")
    if st.get("stats_enabled"):
        A("listen stats")
        A("    bind %s" % (st.get("stats_bind") or "127.0.0.1:8404"))
        A("    mode http")
        A("    stats enable")
        A("    stats uri %s" % (st.get("stats_uri") or "/stats"))
        A("    stats refresh 10s")
        A("")

    # Everyone who may be asked to sign in, in one list. Written before the
    # services so it reads in the order it is used: who exists, then what they
    # are let into.
    for ln in access.render_userlist(cfg):
        A(ln)

    for fe in hp["frontends"]:
        if not fe.get("enabled", True):
            continue
        mode = fe.get("mode", "http")
        A("frontend fe_%s" % _sec(fe["name"]))
        ssl_suffix = ""
        if fe.get("ssl_enabled"):
            crts = [str(cert_path(certs[cid])) for cid in (fe.get("certificates") or []) if cid in certs]
            # HAProxy truncates a configuration line after 64 words, and every
            # certificate costs two of them ("crt" and its path), so a listener
            # with enough HTTPS services silently loses the rest and fails to
            # parse. Past a safe count, point it at the directory instead: every
            # certificate this app deploys lives there, and SNI picks the right
            # one either way.
            if len(crts) > MAX_INLINE_CERTS:
                A("    # %d certificates: loading the whole directory, because a"
                  % len(crts))
                A("    # bind line cannot name that many.")
                crts = []
            if crts:
                ssl_suffix = " ssl " + " ".join("crt " + p for p in crts)
            else:
                ssl_suffix = " ssl crt %s/" % CERT_DIR
            if fe.get("http2"):
                ssl_suffix += " alpn h2,http/1.1"
        for b in (fe.get("binds") or "").splitlines():
            if b.strip():
                A("    bind %s%s" % (b.strip(), ssl_suffix))
        A("    mode %s" % mode)
        A("    option httplog" if mode == "http" else "    option tcplog")
        if mode == "http" and fe.get("forwardfor", True):
            A("    option forwardfor")
        # HAProxy runs every http-request rule before any use_backend, whatever
        # order they appear in, and warns on each reload when the file does not
        # say so. Group them the way it will actually evaluate them: ACLs, then
        # request rules, then routing.
        acls, requests, routes = [], [], []

        if mode == "http" and fe.get("ssl_enabled"):
            requests.append("http-request set-header X-Forwarded-Proto https if { ssl_fc }")
        if acme_on and mode == "http":
            acls.append("acl acme_challenge path_beg /.well-known/acme-challenge/")
            routes.append("use_backend bk_acme_challenge if acme_challenge")
        if mode == "http" and fe.get("http_to_https") and not fe.get("ssl_enabled"):
            excl = " if !acme_challenge !{ ssl_fc }" if acme_on else " unless { ssl_fc }"
            requests.append("http-request redirect scheme https code 301" + excl)

        # named ACLs for every condition referenced by this frontend's rules
        used = []
        for rid in fe.get("rules") or []:
            r = rules.get(rid)
            for cid in (r.get("conditions") or []) if r else []:
                if cid in conds and cid not in used:
                    used.append(cid)
        need_inspect = False
        for cid in used:
            c = conds[cid]
            expr = COND_MAP.get(c.get("type", "custom"), COND_MAP["custom"])(c)
            acls.append("acl acl_%s %s" % (_sec(c["name"]), expr))
            if mode == "tcp" and c.get("type") == "ssl_sni":
                need_inspect = True
        if need_inspect:
            requests.append("tcp-request inspect-delay 5s")
            requests.append("tcp-request content accept if { req_ssl_hello_type 1 }")

        for rid in fe.get("rules") or []:
            r = rules.get(rid)
            if not r:
                continue
            ln = _rule_line(r, conds, backends)
            if not ln:
                continue
            # Relative order is preserved inside each group, so first-match
            # routing and rule precedence are unchanged.
            (routes if ln.startswith("use_backend") else requests).append(ln)

        for ln in acls + requests + routes:
            A("    " + ln)

        db = backends.get(fe.get("default_backend"))
        if db:
            A("    default_backend be_%s" % _sec(db["name"]))
        for ln in (fe.get("custom") or "").splitlines():
            if ln.strip():
                A("    " + ln.strip())
        A("")

    if acme_on:
        A("backend bk_acme_challenge")
        A("    mode http")
        A("    server acme_sh 127.0.0.1:%s" % ac.get("challenge_port", 9080))
        A("")

    for be in hp["backends"]:
        if not be.get("enabled", True):
            continue
        mode = be.get("mode", "http")
        A("backend be_%s" % _sec(be["name"]))
        A("    mode %s" % mode)
        A("    balance %s" % be.get("balance", "roundrobin"))
        hc = checks.get(be.get("healthcheck")) if be.get("healthcheck_enabled") else None
        inter = (hc.get("interval") if hc else None) or "2s"
        if hc:
            htype = hc.get("type")
            if htype == "http":
                # An HTTP check can front a TCP service -- Patroni's /master on
                # 8008 deciding which PostgreSQL takes connections on 5432.
                method = hc.get("http_method", "GET")
                uri = hc.get("http_uri", "/")
                ver, host_hdr = hc.get("http_version"), hc.get("http_host")
                if ver or host_hdr:
                    # the form that can carry a version and headers
                    A("    option httpchk")
                    send = "    http-check send meth %s uri %s" % (_sec(method), uri)
                    if ver in ("HTTP/1.0", "HTTP/1.1", "HTTP/2"):
                        send += " ver %s" % ver      # the slash must survive sanitising
                    if host_hdr:
                        send += " hdr Host %s" % _sec(host_hdr)
                    A(send)
                else:
                    A("    option httpchk %s %s" % (method, uri))
                if hc.get("expect_status"):
                    A("    http-check expect status %s" % hc["expect_status"])
            elif htype == "ssl":
                A("    option ssl-hello-chk")
            elif htype == "pgsql":
                # HAProxy opens a PostgreSQL startup packet as this user; the
                # server only has to answer the handshake, no password is sent.
                A("    option pgsql-check user %s" % _sec(hc.get("db_user") or "postgres"))
            elif htype == "mysql":
                A("    option mysql-check user %s%s" % (_sec(hc.get("db_user") or "haproxy"),
                                                        " post-41" if hc.get("mysql_post41", True) else ""))
            # "tcp" needs nothing here: `check` on the server line is a connect test
        if be.get("log_health_checks"):
            A("    option log-health-checks")
        # Maintenance: every request answered 503, cleanly, while the servers
        # and their health checks stay exactly as they were -- pausing a
        # service must not look like the service breaking, and resuming must
        # not wait for checks to pass again. First among the rules, so it
        # wins over the allow-list and the sign-in.
        if be.get("maintenance"):
            if mode == "http":
                A('    http-request return status 503 content-type "text/plain" '
                  'string "This service is down for maintenance."')
            else:
                A("    tcp-request content reject")
        # Who may reach this pool by source address. Works for TCP too --
        # unlike the sign-in, an address needs no place in the protocol to
        # carry it. A list where every entry is malformed refuses everyone:
        # dropping the list because it could not be read would open the
        # service to exactly the people it names by not naming them.
        if (be.get("allow_src") or "").strip():
            nets, bad = access.networks(be.get("allow_src"))
            for token in bad:
                A("    # not a valid network, left out: %s" % _sec(token))
            deny = "http-request deny" if mode == "http" else "tcp-request content reject"
            if nets:
                A("    %s unless { src %s }" % (deny, " ".join(nets)))
            else:
                A("    # every allowed network is malformed, so nobody is")
                A("    " + deny)
        # A sign-in in front of this pool. HAProxy checks it against the
        # userlist itself, so a request without credentials is answered with a
        # 401 here and never reaches a server. Only in HTTP mode: there is no
        # such thing as basic authentication on a raw TCP port.
        if be.get("auth_enabled") and mode == "http":
            wanted = be.get("auth_groups") or []
            allowed = [_sec(n) for n in access.group_names(cfg, wanted)]
            # Addresses that are trusted without a password -- the LAN, most
            # of the time. They go in front of both halves below: they skip
            # the prompt, and they still get in when nobody else could.
            exempt, _bad = access.networks(be.get("auth_exempt_src") or "")
            skip = ("{ src %s } or " % " ".join(exempt)) if exempt else ""
            if not access.users_with_passwords(cfg) or (wanted and not allowed):
                # Either nobody can give the sign-in this service asks for, or
                # the only groups it admits no longer exist. Refusing every
                # request is the one safe reading: serving it openly would turn
                # a missing user or a deleted group into no protection at all.
                A("    # a sign-in is required here and nobody can satisfy it")
                if exempt:
                    A("    http-request deny unless { src %s }" % " ".join(exempt))
                else:
                    A("    http-request deny")
            else:
                # No group named means anybody in the list, which is what the
                # form says an empty selection does.
                test = ("http_auth_group(%s) %s" % (access.USERLIST, " ".join(allowed))
                        if allowed else "http_auth(%s)" % access.USERLIST)
                # The realm is what the browser shows above its password box,
                # so it keeps its spaces and is quoted rather than sanitised
                # into something nobody would recognise.
                realm = re.sub(r'["\\\n]', "", be.get("auth_realm") or be.get("name") or "Restricted")
                A('    http-request auth realm "%s" unless %s{ %s }' % (realm, skip, test))
        for key, directive in (("timeout_connect", "timeout connect"),
                               ("timeout_server", "timeout server"),
                               ("timeout_check", "timeout check")):
            if be.get(key):
                A("    %s %s" % (directive, _sec(str(be[key]))))
        use_cookie = be.get("persistence") == "cookie" and mode == "http"
        if use_cookie:
            A("    cookie %s insert indirect nocache" % (be.get("cookie_name") or "SRVID"))
        elif be.get("persistence") == "source":
            # Pin a client to one server by source address -- the usual choice
            # for TCP services, where there is no cookie to work with.
            # HAProxy spells the IPv4 type "ip"; "ipv4" is rejected outright.
            stype = be.get("stick_type") if be.get("stick_type") in ("ip", "ipv6") else "ip"
            A("    stick-table type %s size %s expire %s" % (
                stype, _sec(be.get("stick_size") or "50k"), _sec(be.get("stick_expire") or "30m")))
            A("    stick on src")
        for sid in be.get("servers") or []:
            sv = servers.get(sid)
            if not sv or not sv.get("enabled", True):
                continue
            parts = ["server %s %s:%s" % (_sec(sv["name"]), sv.get("address", ""), sv.get("port", ""))]
            if be.get("healthcheck_enabled"):
                parts.append("check inter %s" % inter)
                if sv.get("check_port"):
                    parts.append("port %s" % _sec(str(sv["check_port"])))
            if sv.get("weight"):
                parts.append("weight %s" % sv["weight"])
            if sv.get("ssl"):
                parts.append("ssl")
                parts.append("verify required" if sv.get("ssl_verify") else "verify none")
            if sv.get("backup"):
                parts.append("backup")
            if use_cookie:
                parts.append("cookie %s" % _sec(sv["name"]))
            A("    " + " ".join(parts))
        for ln in (be.get("custom") or "").splitlines():
            if ln.strip():
                A("    " + ln.strip())
        A("")

    return "\n".join(L).rstrip() + "\n"


# --------------------------------------------------------------------------
# keepalived.conf renderer
