"""The keepalived.conf renderer."""

from datetime import datetime
from datetime import timezone
import re


# --------------------------------------------------------------------------

def render_keepalived(cfg):
    """Cluster-wide VRRP settings come from cfg["cluster"]; the rest is per node."""
    k = cfg["local"]["keepalived"]
    cl = cfg["cluster"]
    L = []
    A = L.append
    A("# Generated by haproxy-manager at %s" % datetime.now(timezone.utc).isoformat(timespec="seconds"))
    A("# Generated from the cluster settings plus this node's own.")
    A("")
    if cl.get("track_haproxy", True):
        # keepalived >= 2.0 refuses to load a config with tracking scripts
        # unless script security is enabled explicitly.
        A("global_defs {")
        A("    enable_script_security")
        A("    script_user root")
        A("}")
        A("")
        A("vrrp_script chk_haproxy {")
        A('    script "/usr/bin/pgrep -x haproxy"')
        A("    interval 2")
        A("    fall 2")
        A("    rise 2")
        A("    weight -30")
        A("}")
        A("")
    A("vrrp_instance HAPROXY_VIP {")
    A("    state %s" % cl.get("state", "BACKUP"))
    A("    interface %s" % k.get("interface", "eth0"))
    A("    virtual_router_id %s" % cl.get("vrid", 51))
    A("    priority %s" % k.get("priority", 100))
    A("    advert_int %s" % cl.get("advert_int", 1))
    if cl.get("nopreempt"):
        A("    nopreempt")
    if cl.get("auth_pass"):
        A("    authentication {")
        A("        auth_type PASS")
        A("        auth_pass %s" % cl["auth_pass"][:8])  # keepalived uses max 8 chars
        A("    }")
    # Unicast VRRP: list every OTHER node. The source address is optional --
    # keepalived falls back to the interface's own address.
    peers = [p.strip() for p in re.split(r"[\s,]+", k.get("unicast_peer") or "") if p.strip()]
    if peers:
        if k.get("unicast_src"):
            A("    unicast_src_ip %s" % k["unicast_src"].strip())
        A("    unicast_peer {")
        for p in peers:
            A("        " + p)
        A("    }")
    A("    virtual_ipaddress {")
    for v in (cl.get("vips") or "").splitlines():
        if v.strip():
            A("        " + v.strip())
    A("    }")
    if cl.get("track_haproxy", True):
        A("    track_script {")
        A("        chk_haproxy")
        A("    }")
    for ln in (cl.get("custom") or "").splitlines():
        if ln.strip():
            A("    " + ln.strip())
    A("}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------
# apply / preview / status
