"""The keepalived.conf renderer, and the script VRRP tracks HAProxy with."""

from datetime import datetime
from datetime import timezone
import os
import re

from .base import KEEPALIVED_CFG, STATS_SOCK, log

# Written beside keepalived.conf, by the same code that writes it, so the
# configuration can never name a script that is not there yet.
TRACK_SCRIPT = KEEPALIVED_CFG.parent / "ham-haproxy-alive"

# A hung HAProxy -- process alive, accepting nothing -- keeps the virtual IP if
# the only question asked is whether a process exists. This asks HAProxy
# itself, over the admin socket, with a timeout: no answer is a failure, and
# the node hands the address to one that works.
#
# With no socket to ask it answers the older question instead of failing.
# Failing would take the virtual IP away from a node whose HAProxy is fine but
# whose admin socket was never configured -- an outage caused by a health
# check.
TRACK_SCRIPT_BODY = '\n'.join([
    "#!/usr/bin/env python3",
    '"""Exit 0 while HAProxy is answering.',
    "",
    "Written by haproxy-manager; edits are overwritten on the next Apply.",
    '"""',
    "import os",
    "import socket",
    "import subprocess",
    "import sys",
    "",
    "SOCK = %r",
    "TIMEOUT = 1.5",
    "",
    "if not os.path.exists(SOCK):",
    '    sys.exit(subprocess.call(["pgrep", "-x", "haproxy"],',
    "                             stdout=subprocess.DEVNULL,",
    "                             stderr=subprocess.DEVNULL))",
    "try:",
    "    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)",
    "    s.settimeout(TIMEOUT)",
    "    s.connect(SOCK)",
    '    s.sendall(b"show info\\n")',
    '    seen = b""',
    '    while b"Name:" not in seen:',
    "        chunk = s.recv(4096)",
    "        if not chunk:",
    "            break",
    "        seen += chunk",
    "    s.close()",
    "except Exception:",
    "    sys.exit(1)",
    'sys.exit(0 if b"Name:" in seen else 1)',
    "",
])


def write_track_script():
    """Put the tracking script on disk, next to the configuration that names it.

    Root-owned and not writable by anyone else: keepalived refuses to run a
    script it does not trust once enable_script_security is set.
    """
    try:
        TRACK_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
        TRACK_SCRIPT.write_text(TRACK_SCRIPT_BODY % str(STATS_SOCK))
        os.chmod(TRACK_SCRIPT, 0o700)
        return True
    except OSError as e:
        log.warning("could not write the HAProxy tracking script %s: %s", TRACK_SCRIPT, e)
        return False


# --------------------------------------------------------------------------

def render_keepalived(cfg):
    """Cluster-wide VRRP settings come from cfg["cluster"]; the rest is per node."""
    k = cfg["local"]["keepalived"]
    cl = cfg["cluster"]
    L = []
    A = L.append
    A("# Generated by haproxy-manager at %s" % datetime.now(timezone.utc).isoformat(timespec="seconds"))
    A("# Generated from the cluster settings plus this node's own.")
    A("")
    if cl.get("track_haproxy", True):
        # keepalived >= 2.0 refuses to load a config with tracking scripts
        # unless script security is enabled explicitly.
        A("global_defs {")
        A("    enable_script_security")
        A("    script_user root")
        A("}")
        A("")
        A("vrrp_script chk_haproxy {")
        if cl.get("track_mode", "responding") == "process":
            A('    script "/usr/bin/pgrep -x haproxy"')
        else:
            # Asks HAProxy whether it is serving, not merely whether it exists.
            A('    script "%s"' % TRACK_SCRIPT)
            A("    timeout 3")
        A("    interval 2")
        A("    fall 2")
        A("    rise 2")
        A("    weight -30")
        A("}")
        A("")
    A("vrrp_instance HAPROXY_VIP {")
    A("    state %s" % cl.get("state", "BACKUP"))
    A("    interface %s" % k.get("interface", "eth0"))
    A("    virtual_router_id %s" % cl.get("vrid", 51))
    A("    priority %s" % k.get("priority", 100))
    A("    advert_int %s" % cl.get("advert_int", 1))
    if cl.get("nopreempt"):
        A("    nopreempt")
    if cl.get("auth_pass"):
        A("    authentication {")
        A("        auth_type PASS")
        A("        auth_pass %s" % cl["auth_pass"][:8])  # keepalived uses max 8 chars
        A("    }")
    # Unicast VRRP: list every OTHER node. The source address is optional --
    # keepalived falls back to the interface's own address.
    peers = [p.strip() for p in re.split(r"[\s,]+", k.get("unicast_peer") or "") if p.strip()]
    if peers:
        if k.get("unicast_src"):
            A("    unicast_src_ip %s" % k["unicast_src"].strip())
        A("    unicast_peer {")
        for p in peers:
            A("        " + p)
        A("    }")
    A("    virtual_ipaddress {")
    for v in (cl.get("vips") or "").splitlines():
        if v.strip():
            A("        " + v.strip())
    A("    }")
    if cl.get("track_haproxy", True):
        A("    track_script {")
        A("        chk_haproxy")
        A("    }")
    for ln in (cl.get("custom") or "").splitlines():
        if ln.strip():
            A("    " + ln.strip())
    A("}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------
# apply / preview / status
